# Global settings applied to the whole site.
#
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
base    = "docs"
command = "pnpm generate"
publish = "dist"
ignore  = "git diff --quiet HEAD^ HEAD . ../package.json ../netlify.toml"

[[redirects]]
	from = "https://prismic-module.netlify.app/*"
	to = "https://prismic.nuxtjs.org/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://v3.prismic.nuxtjs.org/*"
	to = "https://prismic.nuxtjs.org/:splat"
	status = 301
	force = true
