blank_issues_enabled: false
contact_links:
  - name: 🎙 Nuxt Community Discord
    url: https://discord.nuxtjs.org
    about: Nuxt Community Discord is a nice place to ask your questions and get live support by the community!
  - name: 👪 Prismic Community Forum
    url: https://community.prismic.io
    about: Ask a question about the package or raise an issue directly related to Prismic. You will usually get support there more quickly!
